services:

  postgres:
    image: postgres:17
    container_name: svs-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend

    container_name: svs-backend

    env_file:
      - ./backend/.env

    environment:
      DB_HOST: postgres
      DB_PORT: 5432

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      postgres:
        condition: service_healthy


  certificate-authority:
    build:
      context: ./certificate-authority

    container_name: svs-certificate-authority

    ports:
      - "8001:8001"

    volumes:
      - ca_keys:/app/keys

    depends_on:
      - postgres


  frontend:
    build:
      context: ./frontend

    container_name: svs-frontend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    command: npm run dev

    depends_on:
      - backend


volumes:
  postgres_data:
  ca_keys: