"""update certificate model

Revision ID: 6d6e0199d800
Revises: 8eaf888b689c
Create Date: 2026-08-16 11:15:04.576380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6e0199d800'
down_revision: Union[str, Sequence[str], None] = '8eaf888b689c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('public_key', sa.Text(), nullable=False), schema='certificateauthority')
    op.add_column('certificate', sa.Column('issued_at', sa.DateTime(), nullable=False), schema='certificateauthority')
    op.add_column('certificate', sa.Column('expires_at', sa.DateTime(), nullable=False), schema='certificateauthority')
    op.add_column('certificate', sa.Column('status', sa.String(length=20), nullable=False), schema='certificateauthority')
    op.create_unique_constraint(None, 'certificate', ['id_user'], schema='certificateauthority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificate', schema='certificateauthority', type_='unique')
    op.drop_column('certificate', 'status', schema='certificateauthority')
    op.drop_column('certificate', 'expires_at', schema='certificateauthority')
    op.drop_column('certificate', 'issued_at', schema='certificateauthority')
    op.drop_column('certificate', 'public_key', schema='certificateauthority')
    # ### end Alembic commands ###
