"""initial schema

Revision ID: 8eaf888b689c
Revises: 
Create Date: 2026-08-07 11:48:20.128317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaf888b689c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS election")
    op.execute("CREATE SCHEMA IF NOT EXISTS certificateauthority")
    op.execute("CREATE SCHEMA IF NOT EXISTS ballotbox")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election',
    sa.Column('id_election', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('election_name', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_election'),
    schema='election'
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username'),
    schema='election'
    )
    op.create_table('option',
    sa.Column('id_option', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_name', sa.String(length=30), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('id_election', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_election'], ['election.election.id_election'], ),
    sa.PrimaryKeyConstraint('id_option'),
    schema='ballotbox'
    )
    op.create_table('certificate',
    sa.Column('id_certificate', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['election.user.id_user'], ),
    sa.PrimaryKeyConstraint('id_certificate'),
    schema='certificateauthority'
    )
    op.create_table('user_election',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_election', sa.Integer(), nullable=False),
    sa.Column('has_voted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_election'], ['election.election.id_election'], ),
    sa.ForeignKeyConstraint(['id_user'], ['election.user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_election'),
    schema='election'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_election', schema='election')
    op.drop_table('certificate', schema='certificateauthority')
    op.drop_table('option', schema='ballotbox')
    op.drop_table('user', schema='election')
    op.drop_table('election', schema='election')

    #op.execute("DROP SCHEMA IF EXISTS ballotbox")
    #op.execute("DROP SCHEMA IF EXISTS certificateauthority")
    #op.execute("DROP SCHEMA IF EXISTS election")
    # ### end Alembic commands ###
