"""add public key to users

Revision ID: b5cf8ca4d201
Revises: 6d6e0199d800
Create Date: 2026-08-17 20:07:20.449809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cf8ca4d201'
down_revision: Union[str, Sequence[str], None] = '6d6e0199d800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_key', sa.Text(), nullable=True), schema='election')
    op.create_unique_constraint(None, 'user', ['public_key'], schema='election')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='election', type_='unique')
    op.drop_column('user', 'public_key', schema='election')
    # ### end Alembic commands ###
